server:
  port: 8761
eureka:
  client:
    registerWithEureka: false # Don’t register with Eureka service.
    fetchRegistry: false # Don’t cache registry information locally.
  server:
    waitTimeInMsWhenSyncEmpty: 5 # Initial time to wait before server takes requests
